# Generated by Django 5.2.7 on 2025-10-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.svg', upload_to='profile_pics/'),
        ),
    ]
