# Generated by Django 5.2.7 on 2025-10-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
