# Generated by Django 5.2.7 on 2025-10-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_name_alter_category_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatsheet',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
