# Generated by Django 5.2.7 on 2025-10-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cheatsheet_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
    ]
